# Generated by Django 3.1.5 on 2021-04-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_pointsuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointsUser',
            new_name='AllPointsUser',
        ),
    ]
