# Generated by Django 3.1.5 on 2021-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210406_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPointsUser2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Points',
            },
        ),
        migrations.DeleteModel(
            name='AllPointsUser',
        ),
    ]
