# Generated by Django 3.1.5 on 2021-04-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210406_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllPointsUser2',
        ),
        migrations.AlterModelTable(
            name='allpoints_user',
            table='UserPoint',
        ),
    ]
