# Generated by Django 3.1.5 on 2021-04-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210406_2137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllPoints_User',
            new_name='User_point',
        ),
        migrations.RenameField(
            model_name='user_point',
            old_name='points_user',
            new_name='total_points',
        ),
        migrations.AlterModelTable(
            name='user_point',
            table='totalPoints',
        ),
    ]
