# Generated by Django 3.1.5 on 2021-04-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210406_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_point',
            new_name='Userpoint',
        ),
    ]
