# Generated by Django 3.1.5 on 2021-04-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20210406_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpoint',
            old_name='totalpoints',
            new_name='totalp',
        ),
        migrations.RemoveField(
            model_name='userpoint',
            name='created',
        ),
        migrations.AlterModelTable(
            name='userpoint',
            table='totalpoints',
        ),
    ]
